site_name: Taterzens
site_url: https://samolego.github.io/Taterzens

repo_url: https://github.com/samolego/Taterzens
repo_name: samolego/Taterzens

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs

  logo: assets/img/logo.png
  icon:
    logo: fontawesome/solid/users
    repo: fontawesome/brands/github
  favicon: assets/img/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: green
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: light green
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

plugins:
  - search
  - mike:
      version_selector: true   # set to false to leave out the version selector
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
      strict: true


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tilde # strikethrough text
  - pymdownx.details # "notes"
  - attr_list #images
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed

extra:
  version:
    provider: mike

